# Generated by Django 4.2.21 on 2025-05-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_financialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='이정연', max_length=100),
            preserve_default=False,
        ),
    ]
