# Generated by Django 4.2.21 on 2025-05-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockknowledge',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
