# Generated by Django 4.2.21 on 2025-05-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('eng_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
