# Generated by Django 4.2.21 on 2025-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('published_at', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
