# Generated by Django 4.2.21 on 2025-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_newsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
