# Generated by Django 4.2.21 on 2025-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_newsitem_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(blank=True, default='금융', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
