# Generated by Django 4.2.21 on 2025-05-25 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_newsitem_category_alter_newsitem_published_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='crawled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitem',
            name='lede',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='press',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='published_at',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
