# Generated by Django 4.2.21 on 2025-05-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
