# Generated by Django 4.2.21 on 2025-05-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_challengeprogress_userchallenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetemplate',
            name='default_unit',
            field=models.CharField(choices=[('day', '일'), ('week', '주'), ('month', '월')], max_length=10),
        ),
    ]
