# Generated by Django 4.2.21 on 2025-05-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_alter_challengetemplate_default_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='unit',
            field=models.CharField(choices=[('day', '일'), ('week', '주'), ('month', '월')], max_length=10),
        ),
    ]
