# Generated by Django 4.2.21 on 2025-05-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_alter_userchallenge_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
